import Head from "next/head";
import SideBar from "../components/SideBar";
export default function Home() {
  return (
    <>
      <Head>
        <title>Box Chat</title>
        <meta name="description" content="Generated by Temo Dev" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
    </>
  );
}
